### ISSUE TITLE
DC-MediaPlayer not working

### ISSUE THREAD

**Issue by kep100** [DC-development/DC-Mediaplayer#2]
I installed MediaPlayer and pointed it to the correct folder.

It DOES show the song titles and buttons.  The buttons appear to work.  I can press them and Previous/Next does make the highlight move from song to song.  However, there is no graphic on the buttons and clicking on a song does not make it play.  The play button does not make a song play either.

I have tried various skins and the behavior is still the same.

I'm using Joomla 3.4.1 if that makes a difference.

Any ideas why this is not working?

BTW, would you have this available as plugin (as opposed to a module) so it can be placed in the content area instead of in a module?

In advance, thank for any light you can shed on this issue.

**Comment by DC-development** [comment]
Hi Kep100, 

thanks for leaving a note !

How exactly did you install the module ? 
What browser (and version) are you using to test?.

**Comment by DC-development** [comment]
(I found something ate the fonts/Icons - ill bring them back)

**Comment by DC-development** [comment]
I think its your dev server not serving the mp3's with correct mime-type.
You can configure that in your .htaccess - like this for example:

''''
<IfModule mod_rewrite.c>
  AddType audio/mp3 .mp3
</IfModule>
''''

**Comment by kep100** [comment]
I installed the player through Joomla's extension manager.

I've tested in the following browsers and versions:
Chrome 42.0.2311,90
Firefox 37.02

I"m also sure that the server is already configured to play mp3 files with no problem.as I have several domains on it that also play mp3 files with no problem whatsoever.

My test audio files are named:
01_Accept_Balls_To_The_Wall.mp3
02_ABC_Be_Near_Me.mp3
03_AC_DC_Back_In_Black.mp3
04_Abba_Dancing_Queen.mp3

**Comment by DC-development** [comment]
Well, ok.

The Icons are  now in the package itself so they should be back. 

Still - make sure your server sends right mimetype - just add the few lines above to your .htaccess
The audio-tag is pretty sensitive about the mimetype.

Otherwise I dont know what the problem is - right now-

**Comment by kep100** [comment]
Should I uninstall the old package and reinstall the new one then?

**Comment by DC-development** [comment]
That should help with the icons.

**Comment by kep100** [comment]
I uninstalled and reinstalled.  I now see the icons but still no sound.

If it helps of means anything, the server is a Windows box running Plesk.  This means that mime types are automatically configured when the domain is installed to play mp3 files.

Additionally, I have no problem playing mp3 files with any other player I've used so I don't think server configuration is the issue.

Not sure if the above info helps you track down the issue but I hope it does.

Thank you for all of your help so far!

**Comment by DC-development** [comment]
you could check network with the chrome dev-tools (F12) - There you might find the files and the mime-type they are delivered with. 

Im pretty sure its that - pleas open a new issue, if you veryfied the .htaccess file in the root of your project does ensure the mime-type for mp3. 

Thx a lot !
