### ISSUE TITLE
Random playback

### ISSUE THREAD

**Issue by Alterscream** [DC-development/DC-Mediaplayer#6]
Good day! What option I need to write in the file player.js what would the tracks are played randomly? Thanks

**Comment by DC-development** [comment]
Good Day to you, too!
Thank you for using our player. Unfortunately theres is no option for that, yet. This feature has to be programmed, yet.  I would suggest another option field in the modules xml wich gets evaluated in a variables section - If you like to I'd be very happy about a pull request with your changes. 

If you don't have the time I'll look into it these days to add this feature (would be cool)
Thanks for your suggestion.

Kind regards

Phil

**Comment by Alterscream** [comment]
Спасибо за быстрый ответ! Мне очень понравился плеер. Установил его на сайт. Применил свои стили, но в итоге обнаружил, что не могу заставить плеер играть треки рандомно. Я был бы очень рад если бы вы добавили такую возможность в ваш замечательный плеер :)

**Comment by DC-development** [comment]
I'll have a look at it.

**Comment by Alterscream** [comment]
In these files I can find the solution of my question? Sorry not very good at programming))

**Comment by DC-development** [comment]
This version of player.js should work.

https://gist.github.com/DC-development/77bcbdf866be75f37cac

**Comment by Alterscream** [comment]
Thank you! I'll try! Yes I use the forward/back buttons, and see how it works, I will answer:)

**Comment by Alterscream** [comment]
Tried, apparently there is no difference:) And really make the track when the page loads has changed, now appears for the first track, all the time:)

**Comment by DC-development** [comment]
No - wait - you'd get me wrong....

Try the latest version I just edited it !

**Comment by DC-development** [comment]
Please let me know if it works now - and maybe you can drop us a line in the reviews section on extensions.joomla.org - that would be very nice.

**Comment by DC-development** [comment]
Hej ? Whats up ? Does this work now for you - because it works just fine for me ... !?

**Comment by Alterscream** [comment]
Used the latest version of your script, but it still always appears as the first track, when the page is refreshed it does not change :( Here's the site where I make changes - http://yoursite2.meridian-web.ru/ . The player is at the top right (Петр Налич...) Just now in Pape player two songs (may need more for the script to work?)

**Comment by DC-development** [comment]
Ok - Ii guess I didn't get you right - the player will now shuffle the tracks when its played by the user and the option is set to true - Its not gonna start playing on  page load - so what you need is autoplay function wich uses the shuffle function... 
Thats a different thing. I will take a look at that, too - please give me some time Im not gonna make it today I fear - I'll get back to you tomorrow about that -ok ? 

Cheers 

Phil

**Comment by Alterscream** [comment]
For example I went to the site for the first time, see in the player Track # 1, I go inward on the page and see Track # 55, I go home again and see Track # 43, i.e., the tracks in the player are given randomly, I mean it :)

Yeah, plus when you click on the next track the track from a folder randomly selected, and different every time.

Sorry for bad English, be sure to leave a review, I think this decision many who will need, ideally such opium to put in the admin:)) But I at least in the script to get the solution

**Comment by DC-development** [comment]
Oh wait - I think I got it ! try this 

https://gist.github.com/DC-development/eb034a5183489f75ed49

**Comment by Alterscream** [comment]
AutoPlay I don't need, I need to randomly change tracks when you open Stranz site ,as well as randomly changing when browsing your tracks :) I Have some reason does not work, change the RFO de where necessary - /modules/mod_dcmediaplayer/js/player.js

**Comment by Alterscream** [comment]
http://www.yoursite2.meridian-web.ru/modules/mod_dcmediaplayer/js/player.js

**Comment by DC-development** [comment]
I see the Problem - hmmmm well not much randomizing with three tracks - 
(Very beautiful music though and I'm impressed by your css-skills - very cool skin you made).
Ok thats something more complicated - so I'd hav to write the last track played to a cookie to know it was played after the page reloads - puhhh - well, ok - seems like a legit usecase. 

Im on it. 
:)

**Comment by Alterscream** [comment]
Insert test content so far, thanks!) Searched for the html5 player, found yours, very fit. Apparently flash on the Rand is easier to do. There is really not a simple task :(

**Comment by DC-development** [comment]
Actually it does exactly what you wanted, now - the random is not that big if you put only three tracks in there - thats it im testing with about 8 to 10 tracks - and I always have adifferent track with every page reload  and skipping ... 
Put some more tracks in it - you'll see.

**Comment by DC-development** [comment]
Got it, I guess 

https://gist.github.com/DC-development/13d7eb3689031f158111

**Comment by Alterscream** [comment]
Poured more tracks, random flipping works! It turns left to change tracks when changing pages, is it real?)

**Comment by DC-development** [comment]
"...It turns left to change tracks..."  o.O - excuse me ? - But yeah its real   ....  hahaha Im laughing my ass off about this track "Пётр Налич - Сахарный пакет"   I dont get a word - but it sounds like big fun.

Are we done then, Dear ?

**Comment by DC-development** [comment]
Yepp - Ithinkn thats it 

https://gist.github.com/DC-development/068721de2181b23157ef

Selects a random track on startup - but doesn't autoplay .... This maybe it ;)

**Comment by Alterscream** [comment]
Thank you! I will try, I will unsubscribe later!

**Comment by DC-development** [comment]
Latest version - should work now - Im happy when you are :) 

see you !

**Comment by DC-development** [comment]
Got rid of a few more bugs...
You didn't give up on me, did you - we're so close now :dart: 

https://gist.github.com/DC-development/068721de2181b23157ef

(Compared to my russian, your english is very good, I guess ;))

**Comment by Alterscream** [comment]
"And dont forget to put some "opium in the admin" ... whatever that means :D"

xD 

Talking to you with this - https://translate.yandex.com/


On my site The first track constantly "Петр Налич - Галя" ) http://yoursite2.meridian-web.ru/o-proekte.html

I would want that the track changed by changing the page :))

I will think how to do it ), I will leave a review on the site ext.joomla

Thanks for help!

**Comment by Alterscream** [comment]
I left a review here http://extensions.joomla.org/extensions/extension/multimedia/multimedia-players/dc-mediaplayer , evidently he left for moderation )

**Comment by DC-development** [comment]
I see it does change the tracks on reload, now. 
Sadly I don't see a review in the extensions-directory. And would you be so kind to put back the backlink in the player or put the backlink somewhere else on your page referring to our developers-site, thanx a lot !

**Comment by Alterscream** [comment]
All right! Reviews on the site joomla ext. are moderated ?

**Comment by DC-development** [comment]
Not by me ... And if they do - they are very slow, I guess.
(And it has to be in English I guess)

**Comment by DC-development** [comment]
HI there
Yes they are - and they are pretty slow I found out.

http://extensions.joomla.org/support/knowledgebase/item/submitting-a-review
