### ISSUE TITLE
The player does play songs in a Multilingual site

### ISSUE THREAD

**Issue by imanickam** [DC-development/DC-Mediaplayer#8]
The player does not play songs in a multilingual site.  Kindly review the topic http://forum.joomla.org/viewtopic.php?f=706&t=891435 in the Joomla Forum.

The analysis of the problem revealed that the path to the media folder does not get resolved.  Adding the URL before the path of the folder does not yield the desired result as the urls may contain language prefix and hence creating problem.

So, adding baseurl to the path resolved the issue.

Hope this helps.

**Comment by DC-development** [comment]
Thank you - I'd be happy about a pull request!

**Comment by imanickam** [comment]
Done... https://github.com/imanickam/DC-Mediaplayer/pull/1/files

**Comment by imanickam** [comment]
I have merged the pull request that I have created.  Hope you do not mind
this.

**Comment by DC-development** [comment]
You merged to your own fork, so why should I mind ;) - Thx for the hint - fixed it in my repo, too.
